# Question 2: Numerical Analysis Using NumPy

## 1. Introduction

This section performs numerical analysis on South African GDP growth and employment data using Python and NumPy.

The dataset contains observations for South Africa across different years and economic sectors. NumPy is used to perform numerical calculations, descriptive statistics, array operations, filtering, reshaping, correlation analysis, and identification of extreme observations.

The purpose of the analysis is to identify important numerical patterns in GDP growth and employment and demonstrate how NumPy can be used to analyse economic data efficiently.

In [62]:
import pandas as pd
import numpy as np

In [66]:
df = pd.read_csv("../../data/final_clean/GDP_Employment_South_Africa_Cleaned.csv")

df.head()

,REF_AREA_LABEL,TIME_PERIOD,GDP_Growth,Employment_Thousands,Sector
0,South Africa,2017,1.157947,16536.302734,Sector: Total
1,South Africa,2017,1.157947,849.620773,Sector: Agriculture
2,South Africa,2017,1.157947,414.533398,Sector: Mining
3,South Africa,2017,1.157947,1855.818421,Sector: Manufacturing
4,South Africa,2017,1.157947,187.111598,Sector: Utilities


In [67]:
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))
print("Columns:")
print(df.columns.tolist())

print("\nCountries:")
print(df["REF_AREA_LABEL"].unique())

print("\nNumber of unique countries:", df["REF_AREA_LABEL"].nunique())

Number of rows: 570
Number of columns: 5
Columns:
['REF_AREA_LABEL', 'TIME_PERIOD', 'GDP_Growth', 'Employment_Thousands', 'Sector']

Countries:
<StringArray>
['South Africa']
Length: 1, dtype: str

Number of unique countries: 1


## 2. Data Quality Verification

Before performing numerical analysis, the dataset is checked for correct data types, missing values, and duplicate observations. This ensures that the NumPy calculations are performed on valid numerical data.

In [68]:
print("Data types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

Data types:
REF_AREA_LABEL              str
TIME_PERIOD               int64
GDP_Growth              float64
Employment_Thousands    float64
Sector                      str
dtype: object

Missing values:
REF_AREA_LABEL          0
TIME_PERIOD             0
GDP_Growth              0
Employment_Thousands    0
Sector                  0
dtype: int64

Duplicate rows:
0


## 3. NumPy Array Conversion

The numerical variables are converted from Pandas Series into NumPy arrays. This allows NumPy functions to be used for statistical calculations and numerical operations.

In [69]:
years = df["TIME_PERIOD"].to_numpy()
gdp_growth = df["GDP_Growth"].to_numpy()
employment = df["Employment_Thousands"].to_numpy()

print("Years array shape:", years.shape)
print("GDP Growth array shape:", gdp_growth.shape)
print("Employment array shape:", employment.shape)

print("\nFirst 10 years:")
print(years[:10])

print("\nFirst 10 GDP Growth values:")
print(gdp_growth[:10])

print("\nFirst 10 Employment values:")
print(employment[:10])

Years array shape: (570,)
GDP Growth array shape: (570,)
Employment array shape: (570,)

First 10 years:
[2017 2017 2017 2017 2017 2017 2017 2017 2017 2017]

First 10 GDP Growth values:
[1.15794695 1.15794695 1.15794695 1.15794695 1.15794695 1.15794695
 1.15794695 1.15794695 1.15794695 1.15794695]

First 10 Employment values:
[16536.30273438   849.62077318   414.53339754  1855.81842055
   187.11159817  1381.0282351   3307.47734866  1026.52085431
  2495.86583723  5018.3255011 ]


## 4. Descriptive Statistics

NumPy statistical functions are used to calculate the mean, median, minimum, maximum, standard deviation, and variance for GDP growth and employment.

These measures provide an overview of the central tendency and variation in the South African economic data.

In [70]:
# GDP Growth statistics
gdp_mean = np.mean(gdp_growth)
gdp_median = np.median(gdp_growth)
gdp_min = np.min(gdp_growth)
gdp_max = np.max(gdp_growth)
gdp_std = np.std(gdp_growth)
gdp_variance = np.var(gdp_growth)

print("GDP Growth Mean:", gdp_mean)
print("GDP Growth Median:", gdp_median)
print("GDP Growth Minimum:", gdp_min)
print("GDP Growth Maximum:", gdp_max)
print("GDP Growth Standard Deviation:", gdp_std)
print("GDP Growth Variance:", gdp_variance)

print("\n" + "="*60 + "\n")

# Employment statistics
employment_mean = np.mean(employment)
employment_median = np.median(employment)
employment_min = np.min(employment)
employment_max = np.max(employment)
employment_std = np.std(employment)
employment_variance = np.var(employment)

print("Employment Mean:", employment_mean)
print("Employment Median:", employment_median)
print("Employment Minimum:", employment_min)
print("Employment Maximum:", employment_max)
print("Employment Standard Deviation:", employment_std)
print("Employment Variance:", employment_variance)

GDP Growth Mean: 3.023583474342852
GDP Growth Median: 3.1000000005441137
GDP Growth Minimum: -2.1370328450052085
GDP Growth Maximum: 7.939608644806768
GDP Growth Standard Deviation: 2.409849529155861
GDP Growth Variance: 5.8073747531727244


Employment Mean: 1870.569163593318
Employment Median: 947.9243344425784
Employment Minimum: 17.798834023718744
Employment Maximum: 16536.302734375
Employment Standard Deviation: 2892.597946701926
Employment Variance: 8367122.881264198


## 5. Range and Percentile Analysis

The range measures the difference between the maximum and minimum values. NumPy's `np.ptp()` function is used to calculate the range.

The 25th, 50th, and 75th percentiles are also calculated to describe the distribution of GDP growth and employment.

In [71]:
# GDP Growth range and percentiles
gdp_range = np.ptp(gdp_growth)
gdp_percentiles = np.percentile(gdp_growth, [25, 50, 75])

print("GDP Growth Range:", gdp_range)
print("GDP Growth 25th, 50th and 75th Percentiles:", gdp_percentiles)

print("\n" + "="*60 + "\n")

# Employment range and percentiles
employment_range = np.ptp(employment)
employment_percentiles = np.percentile(employment, [25, 50, 75])

print("Employment Range:", employment_range)
print("Employment 25th, 50th and 75th Percentiles:", employment_percentiles)

GDP Growth Range: 10.076641489811976
GDP Growth 25th, 50th and 75th Percentiles: [1.41382645 3.1        4.57194475]


Employment Range: 16518.503900351283
Employment 25th, 50th and 75th Percentiles: [ 402.8830962   947.92433444 1779.99505316]


## 6. NumPy Array Reshaping

NumPy arrays can be reshaped into different dimensions without changing their underlying values. Both GDP growth and employment arrays are reshaped from one-dimensional arrays into two-dimensional column arrays.

In [76]:
# Reshape both numerical arrays into column vectors
gdp_reshaped = gdp_growth.reshape(-1, 1)
employment_reshaped = employment.reshape(-1, 1)

print("Original GDP Growth shape:", gdp_growth.shape)
print("Reshaped GDP Growth shape:", gdp_reshaped.shape)

print("\nOriginal Employment shape:", employment.shape)
print("Reshaped Employment shape:", employment_reshaped.shape)

print("\nFirst 5 GDP Growth values after reshaping:")
print(gdp_reshaped[:5])

print("\nFirst 5 Employment values after reshaping:")
print(employment_reshaped[:5])

Original GDP Growth shape: (570,)
Reshaped GDP Growth shape: (570, 1)

Original Employment shape: (570,)
Reshaped Employment shape: (570, 1)

First 5 GDP Growth values after reshaping:
[[1.15794695]
 [1.15794695]
 [1.15794695]
 [1.15794695]
 [1.15794695]]

First 5 Employment values after reshaping:
[[16536.30273438]
 [  849.62077318]
 [  414.53339754]
 [ 1855.81842055]
 [  187.11159817]]


## 07. GDP Growth and Employment Correlation

The Pearson correlation coefficient is calculated using NumPy to measure the linear relationship between GDP growth and employment.

The correlation coefficient ranges from -1 to +1. Values close to +1 indicate a strong positive relationship, values close to -1 indicate a strong negative relationship, and values close to 0 indicate a weak or no linear relationship.

In [77]:
# Calculate correlation coefficient
correlation_matrix = np.corrcoef(gdp_growth, employment)
correlation = correlation_matrix[0, 1]

print("GDP Growth vs Employment correlation:", correlation)

GDP Growth vs Employment correlation: -0.07617816650662264


## 08. Sector-Level Numerical Analysis

The dataset contains employment observations for different economic sectors in South Africa. NumPy is used to calculate the mean employment and mean GDP growth for each sector.

This allows differences in employment levels between sectors to be identified numerically.

In [ ]:
# Create a NumPy-based sector summary

sector_results = []

for sector in sectors:
    sector_mask = df["Sector"].to_numpy() == sector
    
    sector_gdp = gdp_growth[sector_mask]
    sector_employment = employment[sector_mask]
    
    sector_results.append([
        sector,
        np.mean(sector_gdp),
        np.mean(sector_employment),
        np.min(sector_employment),
        np.max(sector_employment)
    ])

sector_results = np.array(sector_results, dtype=object)

print("Sector | Mean GDP Growth | Mean Employment | Min Employment | Max Employment")

for row in sector_results:
    print(
        f"{row[0]} | "
        f"{row[1]:.2f} | "
        f"{row[2]:.2f} | "
        f"{row[3]:.2f} | "
        f"{row[4]:.2f}"
    )

Sector | Mean GDP Growth | Mean Employment | Min Employment | Max Employment
Sector: Total | 3.02 | 9352.85 | 4653.68 | 16536.30
Sector: Agriculture | 3.02 | 1039.69 | 661.44 | 1409.83
Sector: Mining | 3.02 | 473.72 | 334.17 | 657.36
Sector: Manufacturing | 3.02 | 1473.76 | 653.89 | 2159.71
Sector: Utilities | 3.02 | 72.42 | 17.80 | 187.11
Sector: Construction | 3.02 | 642.53 | 221.54 | 1409.38
Sector: Trade services | 3.02 | 2071.34 | 818.11 | 3682.75
Sector: Transport services | 3.02 | 515.61 | 189.06 | 1026.52
Sector: Finance and business services | 3.02 | 831.60 | 136.60 | 2495.87
Sector: Other services | 3.02 | 2232.17 | 810.84 | 5018.33


: 

## 09. Identifying Minimum and Maximum Observations

NumPy's `argmin()` and `argmax()` functions are used to identify the positions of the minimum and maximum values in the GDP Growth and Employment arrays.

The corresponding rows in the dataset are then used to determine the year and sector associated with these extreme values.

In [83]:
# Find indexes of minimum and maximum GDP Growth
gdp_min_index = np.argmin(gdp_growth)
gdp_max_index = np.argmax(gdp_growth)

# Find indexes of minimum and maximum Employment
employment_min_index = np.argmin(employment)
employment_max_index = np.argmax(employment)

print("GDP Growth Minimum:")
print("Value:", gdp_growth[gdp_min_index])
print("Year:", df.iloc[gdp_min_index]["TIME_PERIOD"])
print("Sector:", df.iloc[gdp_min_index]["Sector"])

print("\nGDP Growth Maximum:")
print("Value:", gdp_growth[gdp_max_index])
print("Year:", df.iloc[gdp_max_index]["TIME_PERIOD"])
print("Sector:", df.iloc[gdp_max_index]["Sector"])

print("\nEmployment Minimum:")
print("Value:", employment[employment_min_index])
print("Year:", df.iloc[employment_min_index]["TIME_PERIOD"])
print("Sector:", df.iloc[employment_min_index]["Sector"])

print("\nEmployment Maximum:")
print("Value:", employment[employment_max_index])
print("Year:", df.iloc[employment_max_index]["TIME_PERIOD"])
print("Sector:", df.iloc[employment_max_index]["Sector"])

GDP Growth Minimum:
Value: -2.1370328450052085
Year: 1992
Sector: Sector: Total

GDP Growth Maximum:
Value: 7.939608644806768
Year: 1964
Sector: Sector: Total

Employment Minimum:
Value: 17.798834023718744
Year: 1961
Sector: Sector: Utilities

Employment Maximum:
Value: 16536.302734375
Year: 2017
Sector: Sector: Total


## 10. Sorting and Ranking Employment Values

NumPy sorting functions are used to rank employment values from lowest to highest. This helps identify the smallest and largest employment observations in the dataset.

In [84]:
# Sort employment values

sorted_employment = np.sort(employment)

print("Lowest 10 employment values:")
print(sorted_employment[:10])

print("\nHighest 10 employment values:")
print(sorted_employment[-10:])

Lowest 10 employment values:
[17.79883402 18.26115301 19.78919128 20.67919445 21.60922286 23.38754948
 24.0180168  26.85948457 27.6073459  29.32977994]

Highest 10 employment values:
[14150.99609375 14377.88085938 14595.64648438 14709.78515625
 15076.05371094 15159.45019531 15415.94238281 16130.1015625
 16188.35253906 16536.30273438]
